"""Helpers shared by the config generators."""

from __future__ import annotations

import re

from secret_rules.normalize import _extract_leading_flags, capture_groups

_LOOKAROUND = re.compile(r"\(\?<?[=!]")
_BACKREF = re.compile(r"\\[1-9]")


def re2_compatible(pattern: str) -> bool:
    """True if the pattern avoids constructs RE2 (Go) rejects."""
    return not (_LOOKAROUND.search(pattern) or _BACKREF.search(pattern))


def split_leading_flags(pattern: str) -> tuple[str, str]:
    """Return (flag letters, body) for a canonical pattern."""
    enabled, _disabled, body = _extract_leading_flags(pattern)
    return "".join(sorted(enabled)), body


def ensure_capture_group(pattern: str) -> str:
    """Wrap the whole body in a capture group if the pattern has none
    (noseyparker and titus require at least one)."""
    if capture_groups(pattern):
        return pattern
    flags, body = split_leading_flags(pattern)
    prefix = f"(?{flags})" if flags else ""
    return f"{prefix}({body})"


def id_segment(topic: str) -> str:
    """Make a topic safe for use as one dotted-id segment."""
    return re.sub(r"[^a-z0-9]+", "_", topic.lower()).strip("_")


def header(target: str, rule_count: int, skipped: list[str]) -> str:
    lines = [
        f"# {target} configuration generated by secret-rules.",
        "# Do not edit by hand - regenerate from the referential instead.",
        f"# rules: {rule_count}",
    ]
    if skipped:
        lines.append(f"# skipped (incompatible with {target}): {len(skipped)}")
        for uid in skipped:
            lines.append(f"#   - {uid}")
    return "\n".join(lines) + "\n\n"
