"""Generate a betterleaks TOML config from the referential.

betterleaks shares gitleaks' rule table format but expresses entropy and
stopword filtering as CEL expressions on the finding.
"""

from __future__ import annotations

import json

import tomli_w

from secret_rules.model import Rule
from secret_rules.normalize import capture_groups

from ._common import header, re2_compatible

FILENAME = "betterleaks.toml"


def _cel_filter(rule: Rule) -> str | None:
    parts = []
    if rule.entropy is not None:
        parts.append(f'entropy(finding["secret"]) <= {float(rule.entropy)}')
    if rule.ignore_if_contains:
        words = json.dumps([w for w in sorted(rule.ignore_if_contains)])
        parts.append(f'containsAny(finding["secret"], {words})')
    if not parts:
        return None
    return " || ".join(parts)


def generate(rules: list[Rule]) -> str:
    out_rules = []
    skipped: list[str] = []
    for rule in rules:
        if not re2_compatible(rule.pattern):
            skipped.append(rule.uid)
            continue
        entry: dict = {
            "id": rule.uid,
            "description": rule.description or rule.name,
            "regex": rule.pattern,
        }
        if rule.secret_group and len(capture_groups(rule.pattern)) >= rule.secret_group:
            entry["secretGroup"] = rule.secret_group
        if rule.keywords:
            entry["keywords"] = sorted(rule.keywords)
        cel = _cel_filter(rule)
        if cel:
            entry["filter"] = cel
        out_rules.append(entry)

    doc = {"title": "betterleaks config generated by secret-rules", "rules": out_rules}
    return header("betterleaks", len(out_rules), skipped) + tomli_w.dumps(doc, multiline_strings=True)
