"""Generate a gitleaks TOML config from the referential."""

from __future__ import annotations

import tomli_w

from secret_rules.model import Rule
from secret_rules.normalize import capture_groups

from ._common import header, re2_compatible

FILENAME = "gitleaks.toml"


def generate(rules: list[Rule]) -> str:
    out_rules = []
    skipped: list[str] = []
    for rule in rules:
        if not re2_compatible(rule.pattern):
            skipped.append(rule.uid)
            continue
        entry: dict = {
            "id": rule.uid,
            "description": rule.description or rule.name,
            "regex": rule.pattern,
        }
        if rule.secret_group and len(capture_groups(rule.pattern)) >= rule.secret_group:
            entry["secretGroup"] = rule.secret_group
        if rule.entropy is not None:
            entry["entropy"] = float(rule.entropy)
        if rule.keywords:
            entry["keywords"] = sorted(rule.keywords)
        allowlists = []
        if rule.allowlist_regexes:
            allowlists.append({"regexes": rule.allowlist_regexes})
        if rule.ignore_if_contains:
            allowlists.append(
                {"regexTarget": "match", "stopwords": sorted(k.lower() for k in rule.ignore_if_contains)}
            )
        if allowlists:
            entry["allowlists"] = allowlists
        out_rules.append(entry)

    doc = {"title": "gitleaks config generated by secret-rules", "rules": out_rules}
    return header("gitleaks", len(out_rules), skipped) + tomli_w.dumps(doc)
